fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "intern4@wearevirtua.com"
    sender_name: "intern4@wearevirtua.com"